# Generated by Django 4.2.20 on 2025-04-20 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alternative', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus')], max_length=10)),
                ('genre', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('last_updated_chapter', models.CharField(blank=True, help_text='ID of the last updated chapter', max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('chapters', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
