# Generated by Django 4.2.20 on 2025-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
