# Generated by Django 4.2.20 on 2025-04-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_manga_last_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='chapters',
            new_name='chapter',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter_number', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image_urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga')),
            ],
            options={
                'unique_together': {('manga', 'chapter_number')},
            },
        ),
    ]
