# Generated by Django 4.2.20 on 2025-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_rename_chapters_manga_chapter_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
