# Generated by Django 4.2.20 on 2025-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_chapter_subtitle_alter_chapter_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='mangaowl_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
