# Generated by Django 4.2.20 on 2025-05-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_viewlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewlog',
            unique_together=set(),
        ),
    ]
