# Generated by Django 4.2.20 on 2025-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_viewlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
