# Generated by Django 4.2.20 on 2025-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_chapter_view_count_manga_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['processed'], name='manga_viewl_process_319cad_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['timestamp'], name='manga_viewl_timesta_de9724_idx'),
        ),
    ]
