# Generated by Django 4.2.20 on 2025-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_viewlog_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
